### ISSUE TITLE
Please make your binary releases verifiable

### ISSUE THREAD

**Issue by Giszmo** [ACINQ/phoenix#20]
As [documented in my analysis](https://walletscrutiny.com/posts/fr.acinq.phoenix.mainnet/), it is not easy to verify PlayStore releases of your app. We try to promote verifiability of wallet apps, so internal and external auditors can make sure the app is doing what it promises to do.

To my knowledge build verification is the only way you can protect the users from a release manager adding wallet-stealing routines to the app which under distress or unknowingly due to a virus infecting the build machine might happen to the most ethical release manager.

----

The analysis:

This app recently achieved 1000 downloads, so this is the first time we actually
look at it in detail.

The PlayStore description, below in its entirety:

> Phoenix is a next-generation Bitcoin wallet that lets you send and receive Bitcoin easily.
> 
> Phoenix natively supports Lightning for fast and cheap transactions.

So it's a Bitcoin wallet but no word whether it is custodial or open source.

The website is more clear about those doubts:

> ⚡ Native Lightning support
> 
> 🛡 Non custodial
> 
> 👍 Intuitive and simple UX

and a [link to their GitHub](https://github.com/ACINQ/phoenix).

There, the [build instructions](https://github.com/ACINQ/phoenix/blob/master/BUILD.md)
though are rather vague. Let's see how far we get, as always without using
AndroidStudio and searching for relevant revisions:

```
$ git clone https://github.com/ACINQ/eclair
$ cd eclair
$ git checkout android-phoenix
```

Unfortunately this is as far as get as there is no hint at to which revision
might be relevant to our Phoenix `1.0.1` release:

<div class="language-plaintext highlighter-rouge">
<div class="highlight">
<pre class="highlight">
$ tig
<font color="#3465A4">2020-01-10 15:53 +0100 </font><font color="#4E9A06">dpad85              </font><font color="#3465A4">M</font><font color="#C4A000">─┐</font> <font color="#06989A"><b>[android-phoenix]</b></font> <font color="#C4A000"><b>{origin/android-phoenix}</b></font> Merge branch &apos;android&apos; into android-phoenix
<font color="#3465A4">2020-01-10 14:38 +0100 </font><font color="#4E9A06">sstone              </font><font color="#75507B">│</font><font color="#3465A4"> M</font><font color="#06989A">─┐</font> <font color="#C4A000">{origin/android}</font> Merge branch &apos;master&apos; into android
<font color="#3465A4">2020-01-10 14:37 +0100 </font><font color="#4E9A06">Fabrice Drouin      </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Restore missing &apos;db.close()&apos; methods (#1272)
<font color="#3465A4">2020-01-10 14:56 +0100 </font><font color="#4E9A06">dpad85              </font><font color="#3465A4">o</font><font color="#C4A000"> │</font><font color="#06989A"> │</font> Remove feature graph validation in payment request
<font color="#3465A4">2020-01-10 11:53 +0100 </font><font color="#4E9A06">dpad85              </font><font color="#3465A4">M</font><font color="#C4A000">─│</font><font color="#06989A">─│</font><font color="#C4A000">─┐</font> Merge branch &apos;android&apos; into android-phoenix
<font color="#3465A4">2020-01-09 18:07 +0100 </font><font color="#4E9A06">sstone              </font><font color="#75507B">│</font><font color="#3465A4"> M</font><font color="#06989A">─│</font><font color="#C4A000">─┤</font> Merge branch &apos;master&apos; into android
<font color="#3465A4">2020-01-09 13:47 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font><font color="#06989A">─┘</font> Flat features (#1253)
<font color="#3465A4">2020-01-08 16:47 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Disable Trampoline-MPP to non-Phoenix recipients (#1271)
<font color="#3465A4">2020-01-09 19:39 +0100 </font><font color="#4E9A06">dpad85              </font><font color="#3465A4">M</font><font color="#C4A000">─│</font><font color="#06989A">─│</font><font color="#C4A000">─┐</font> Merge branch &apos;android&apos; into android-phoenix
<font color="#3465A4">2020-01-08 14:09 +0100 </font><font color="#4E9A06">Fabrice Drouin      </font><font color="#75507B">│</font><font color="#3465A4"> o</font><font color="#06989A">─│</font><font color="#C4A000">─┘</font> Fix Outpoint JSON serialization (#1270)
<font color="#3465A4">2020-01-08 12:08 +0100 </font><font color="#4E9A06">sstone              </font><font color="#75507B">│</font><font color="#3465A4"> o</font><font color="#06989A"> │</font> Fix dependency conflict in eclair-node
<font color="#3465A4">2020-01-08 11:46 +0100 </font><font color="#4E9A06">sstone              </font><font color="#75507B">│</font><font color="#3465A4"> M</font><font color="#06989A">─│─┐</font> Merge branch &apos;master&apos; into android
<font color="#3465A4">2020-01-07 16:49 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font><font color="#06989A">─┘</font> Remove mockito from switchboard tests (#1267)
<font color="#3465A4">2020-01-07 16:44 +0100 </font><font color="#4E9A06">Pierre-Marie Padiou </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> More consistency in sending messages during sync (#1268)
<font color="#3465A4">2020-01-06 14:00 +0100 </font><font color="#4E9A06">sstone              </font><font color="#75507B">│</font><font color="#3465A4"> M</font><font color="#06989A">─│─┐</font> Merge branch &apos;master&apos; into android
<font color="#3465A4">2019-12-24 14:06 +0200 </font><font color="#4E9A06">Anton Kumaigorodski </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font><font color="#06989A">─┘</font> Remove repeated code (#1265)
<font color="#3465A4">2019-12-24 02:11 -0600 </font><font color="#4E9A06">Mike W. Erwin       </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Added some instructions for TOR auth (#1262)
<font color="#3465A4">2019-12-18 16:39 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Improve CommandSend type (#1260)
<font color="#3465A4">2019-12-18 14:34 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Relay Trampoline payments (#1220)
<font color="#3465A4">2019-12-17 10:41 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Update Maven (3.6.3) (#1259)
<font color="#3465A4">2019-12-12 09:22 +0100 </font><font color="#4E9A06">Dominique           </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Add synchronization when locking database connection (#1200)
<font color="#3465A4">2019-12-11 15:40 +0200 </font><font color="#4E9A06">Anton Kumaigorodski </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Add HasHtlcIdCommand trait (#1245)
<font color="#3465A4">2019-12-11 14:16 +0100 </font><font color="#4E9A06">Pierre-Marie Padiou </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Better randomization of reconnection delay (#1250)
<font color="#3465A4">2019-12-11 14:03 +0100 </font><font color="#4E9A06">Pierre-Marie Padiou </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Minor: missing log category in peer (#1241)
<font color="#3465A4">2019-12-11 13:53 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> MPP: don&apos;t retry if failure comes from final recipient (#1246)
<font color="#3465A4">2019-12-10 13:40 +0100 </font><font color="#4E9A06">Pierre-Marie Padiou </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Minor: ignore &quot;disconnecting&quot; message in Channel (#1231)
<font color="#3465A4">2019-12-09 16:18 +0100 </font><font color="#4E9A06">Fabrice Drouin      </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Add a configurable time-out to onchain fee provider requests (#1244)
<font color="#3465A4">2019-12-09 14:12 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Fix MPP flaky test (#1243)
<font color="#3465A4">2019-12-06 14:23 +0100 </font><font color="#4E9A06">Pierre-Marie Padiou </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> added blank lines to minimize conflicts (#1236)
<font color="#3465A4">2019-12-06 13:57 +0100 </font><font color="#4E9A06">Pierre-Marie Padiou </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Set `akka.loglevel` to `DEBUG` (#1235)
<font color="#3465A4">2019-12-04 17:29 +0100 </font><font color="#4E9A06">Dominique           </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Fix outgoing payments order in payments overview (#1232)
<font color="#3465A4">2019-12-04 14:17 +0100 </font><font color="#4E9A06">Pierre-Marie Padiou </font><font color="#75507B">│</font><font color="#C4A000"> │</font><font color="#3465A4"> o</font> Added a &apos;category&apos; in logs (#1227)
<font color="#3465A4">2019-12-23 15:03 +0100 </font><font color="#4E9A06">dpad85              </font><font color="#3465A4">o</font><font color="#C4A000"> │</font><font color="#06989A"> │</font> Keep connection to peer even with no channels
<font color="#3465A4">2019-12-23 12:25 +0100 </font><font color="#4E9A06">dpad85              </font><font color="#3465A4">o</font><font color="#C4A000"> │</font><font color="#06989A"> │</font> Back to development version
<font color="#3465A4">2019-12-05 15:17 +0100 </font><font color="#4E9A06">dpad85              </font><font color="#3465A4">o</font><font color="#C4A000"> │</font><font color="#06989A"> │</font> Release v0.3.4-android-phoenix
<font color="#3465A4">2019-12-09 17:24 +0100 </font><font color="#4E9A06">pm47                </font><font color="#3465A4">o</font><font color="#C4A000"> │</font><font color="#06989A"> │</font> peer-backup: use a tlv-ready encoding
<font color="#3465A4">2019-12-09 16:18 +0100 </font><font color="#4E9A06">Fabrice Drouin      </font><font color="#3465A4">o</font><font color="#C4A000"> │</font><font color="#06989A"> │</font> Add a configurable time-out to onchain fee provider requests (#1244)
<font color="#3465A4">2019-12-05 19:36 +0100 </font><font color="#4E9A06">pm47                </font><font color="#3465A4">o</font><font color="#C4A000"> │</font><font color="#06989A"> │</font> write channel state in db on restore
<font color="#3465A4">2019-12-05 10:58 +0100 </font><font color="#4E9A06">pm47                </font><font color="#3465A4">o</font><font color="#C4A000"> │</font><font color="#06989A"> │</font> support phoenix features
<font color="#3465A4">2019-12-04 17:29 +0100 </font><font color="#4E9A06">Dominique           </font><font color="#3465A4">o</font><font color="#C4A000"> │</font><font color="#06989A"> │</font> Fix outgoing payments order in payments overview (#1232)
<font color="#3465A4">2019-12-02 16:26 +0100 </font><font color="#4E9A06">pm47                </font><font color="#3465A4">M</font><font color="#C4A000">─┤</font><font color="#06989A">  </font> Merge branch &apos;master&apos; into android
<font color="#3465A4">2019-12-02 16:15 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#3465A4"> o</font> Handle chain re-org in balance computation (#1228)
<font color="#3465A4">2019-12-02 11:40 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#3465A4"> o</font> Fix onion codec test (#1229)
<font color="#3465A4">2019-12-02 11:35 +0100 </font><font color="#4E9A06">Dominique           </font><font color="#75507B">│</font><font color="#3465A4"> o</font> High level payments overview method (#1225)
<font color="#3465A4">2019-12-02 11:06 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#3465A4"> o</font> Rework truncated integers codecs (#1212)
<font color="#3465A4">2019-11-29 17:03 +0100 </font><font color="#4E9A06">Pierre-Marie Padiou </font><font color="#75507B">│</font><font color="#3465A4"> o</font> Extended doHandle to other messages in MultiPartHandler (#1226)
<font color="#3465A4">2019-11-29 10:43 +0100 </font><font color="#4E9A06">Bastien Teinturier  </font><font color="#75507B">│</font><font color="#3465A4"> o</font> Avoid incoherent payment request features. (#1222)
<font color="#3465A4">2019-11-29 15:54 +0100 </font><font color="#4E9A06">sstone              </font><font color="#3465A4">M</font><font color="#C4A000">─│─┐</font> Merge branch &apos;master&apos; into android
</pre>
</div>
</div>

To avoid issues like this, the app repository should reference the library
repository as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

As we won't try out compiling many times the library to try and guess, we
conclude this analysis with the verdict **not verifiable**.

**Comment by sstone** [comment]
The latest release of eclair has deterministic builds (see https://github.com/ACINQ/eclair/releases/tag/v0.3.3) and we've merged support for deterministic builds for Phoenix (which is based on eclair) as well so we should have deterministic builds for the next released apk (see https://github.com/ACINQ/phoenix/pull/24)

**Comment by Giszmo** [comment]
Please bump this issue again once I can get a verifiable Phoenix from Google Play!

**Comment by Giszmo** [comment]
How are things going? Should it be deterministic now?

**Comment by t-bast** [comment]
Same as https://github.com/ACINQ/eclair-mobile/issues/232, we are making progress towards that but it's still not 100% complete.

**Comment by dpad85** [comment]
> 
> 
> Please bump this issue again once I can get a verifiable Phoenix from Google Play!

Hi, v1.3.0 was built using the deterministic build, so you should be able to verify the build. 

You can find the release here: https://github.com/ACINQ/phoenix/releases/tag/v1.3.0
The instructions are available here: https://github.com/ACINQ/phoenix/blob/master/BUILD.md

Note that you need to build the eclair-core and tor libraries with Ubuntu 19.10 to get the same hash. This will be improved, but for now I think it's a good first step. 

Let me know if you have issues.

**Comment by Giszmo** [comment]
That is great news! I looked into it but as the two dependencies eclair and tor library are not versioned, it would only randomly work if it did. I created [this PR](https://github.com/ACINQ/phoenix/pull/43) for your consideration.

I see you are working with `git submodule` in `Tor_Onion_Proxy_Library/external/pluto` already. Anyway, after checking out my PR, just run `git submodule update --init --recursive`

**Comment by Giszmo** [comment]
So I still followed the build instructions and ended up with:

```
[INFO] 
[INFO] --- git-commit-id-plugin:2.2.3:revision (default) @ eclair-core_2.11 ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eclair_2.11 0.3.9-android-phoenix-SNAPSHOT:
[INFO] 
[INFO] eclair_2.11 ........................................ SUCCESS [03:54 min]
[INFO] eclair-core_2.11 ................................... FAILURE [01:46 min]
[INFO] eclair-node ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:41 min
[INFO] Finished at: 2020-04-08T00:51:55Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.3:revision (default) on project eclair-core_2.11: Could not complete Mojo execution...: Error: Could not get HEAD Ref, are you sure you have set the dotGitDirectory property of this plugin to a valid path? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :eclair-core_2.11
root@66e45d38fc87:/mnt# history
    1  apt update
    2  apt full-upgrade
    6  apt install openjdk-11-jdk maven
    8  mvn package -DskipTests
```

That looks like [this closed although unresolved issue](https://github.com/prestodb/presto/issues/11956).

It happened inside a docker: `/tmp/phoenix/eclair$ docker run -it --rm -v$PWD:/mnt --workdir=/mnt ubuntu:19.10`.

Installing `git` did not resolve the issue.

**Comment by dpad85** [comment]
> I looked into it but as the two dependencies eclair and tor library are not versioned

That is not correct. As you can see for version [1.3.0](https://github.com/ACINQ/phoenix/blob/a6aee6d6e1aea8313278190293ef05ff38b71447/app/build.gradle#L136) version we use eclair-core `0.3.8-android-phoenix`. And same for the tor wrapper.

I agree this is not very handy, because it forces the user to actually look into the gradle files and check the dependencies version. While this can be expected from a developer who will often work with snapshot dependencies, and as such will build them, if you just want to build the app it can be annoying. 

Fortunately, as I mentioned, we are working on improving the docker build so that the user does not have to worry about dependencies if he just want to get the actual APK.

Another solution would be that releases do not use dependencies that are not pusblished to a public Maven repository. Meaning, ACINQ publishes `eclair-core` and the tor wrapper lib to Maven Central. However this would mean more work for us.



Note that you are building eclair-core 0.3.9-android-phoenix-SNAPSHOT in your latest build.

**Comment by Giszmo** [comment]
Apologies. I had not seen the reference in the gradle file. I would wait for the improved docker builds but if those don't get merged, I could also automate getting those tags from the gradle file for build automation.

> Another solution would be that releases do not use dependencies that are not pusblished to a public Maven repository. Meaning, ACINQ publishes eclair-core and the tor wrapper lib to Maven Central. However this would mean more work for us.

For the purpose of https://WalletScrutiny.com that is another can of worms: How can we apply the same quality standards we apply to the app itself to all dependencies? How can we distinguish dependencies that are probably ok and that are likely to be used in an attack on the user? Certainly I would consider libraries by the provider of a wallet as very relevant to inspect deeper, so reproducibility here is not optional.

**Comment by Giszmo** [comment]
Sorry guys, I need a bit more help here. So obviously when verifying hopefully hundreds of wallets - but as a good advise anyway - I don't want to have anything installed to my system, so I'm using Docker all the way for compiling stuff, yet the instructions on [how to build phoenix deterministically](https://github.com/ACINQ/phoenix/blob/master/BUILD.md#how-to-build-phoenix-deterministically) require "Eclair-core published in your local maven repo".

The Eclair [build instructions](https://github.com/ACINQ/eclair/blob/master/BUILD.md#build) don't talk about anything being "published in your local maven repo" but I guess that is the `-v $HOME/.m2:/root/.m2` part in the docker command.

So I think I'm close now and only need the part where eclair-core ends up in `/root/.m2` and I can rescue that folder from one docker build to the next, doing this:

```
$ git clone https://github.com/ACINQ/phoenix
$ cd phoenix/
phoenix$ git checkout v1.3.1
phoenix$ cat app/build.gradle | grep "def eclair_version"
  def eclair_version = "0.3.8-android-phoenix"
phoenix$ git clone https://github.com/ACINQ/eclair
phoenix$ cd eclair/
phoenix/eclair$ git checkout v0.3.8-android-phoenix
phoenix/eclair$ mkdir ../m2
phoenix/eclair$ docker run --rm -it \
    -v../m2:/root/.m2 \
    -v$PWD:/mnt \
    --workdir=/mnt ubuntu:19.10 bash
# apt update && \
  apt full-upgrade -y && \
  apt install -y openjdk-11-jdk-headless maven
# mvn package -DskipTests
```

**missing command to publish the results to /root/.m2**

```
# exit
phoenix/eclair$ cd ..
phoenix$ git clone https://github.com/ACINQ/Tor_Onion_Proxy_Library
phoenix$ cat app/build.gradle | grep "def tor"
  def tor_ctl_version = "0.2"
  def tor_wrapper_version = "0.0.3"
phoenix$ cd Tor_Onion_Proxy_Library/
phoenix/Tor_Onion_Proxy_Library$ git tag
v0.0.0
v0.0.2
```

Here I wonder which of those revisions I should pick. `master` is being worked on, so the latest `master` is not stable.

```
phoenix/Tor_Onion_Proxy_Library$ docker run --rm -it \
  --volume ../m2:/root/.m2 \
  --volume $PWD:/mnt \
  --workdir=/mnt mreichelt/android bash
# ./gradlew install
# ./gradlew :universal:build
# ./gradlew :android:build
# exit
```

How do I add this now to the Phoenix project? Again via `~/.m2` somehow?

```
phoenix/Tor_Onion_Proxy_Library$ cd ..
phoenix$ docker build -t phoenix_build .
phoenix$ docker run \
  --rm \
  --volume ./m2:/root/.m2 \
  --volume $(pwd):/home/ubuntu/phoenix/app/build \
  --workdir /home/ubuntu/phoenix \
  phoenix_build ./gradlew assemble
```

**Comment by dpad85** [comment]
Hello, you're right, the build instructions for eclair do not give the command to build the project **and** push the built package to the maven local repository (by default points to `~/.m2`).

So right after you've checked out the eclair-core tag, add:
```
phoenix/eclair$ git checkout v0.3.8-android-phoenix
phoenix/eclair$ mvn clean install -DskipTests <-- missing command
```

For the TOR library, checking out `master` is fine, there's no tag needed because the library is not expected to change. If it does I'll add a tag. Anyway, what is missing is:

```
./gradlew install
./gradlew :universal:build
./gradlew :android:build
./gradlew :android:publishToMaven
```

Note that #48 improves the docker build and you won't have to take care of that anymore! It will be available for the next release (which should happen within the next 2 weeks).

**Comment by dpad85** [comment]
This issue should be fixed by #48 ; let me know if you have any issues. The [build instructions](https://github.com/ACINQ/phoenix/blob/master/BUILD.md#release-phoenix) have been updated and are much more simple. Obviously this will only work for our next releases.

**Comment by Giszmo** [comment]
I tried to follow the build instructions on current master but the Dockerfile failed to build.

```
$ git clone https://github.com/ACINQ/phoenix
$ cd phoenix/
$ docker build -t phoenix_build .

...

Step 12/35 : RUN git clone https://github.com/ACINQ/eclair -b $(cat eclair-core-version.txt)
 ---> Running in 1bfcb01de339
Cloning into 'eclair'...
fatal: Remote branch v0.3.9-android-phoenix-SNAPSHOT not found in upstream origin
The command '/bin/sh -c git clone https://github.com/ACINQ/eclair -b $(cat eclair-core-version.txt)' returned a non-zero code: 128
```

**Comment by dpad85** [comment]
Hello,

It's because the release build does not work with a development version of the app, it's only useful for releases.

If you clone phoenix as is, you will land on the master branch which 99% of the time points to a development commit that uses a development version of eclair-core (aka `SNAPSHOT`). However the docker build is programmed to look for a tag for eclair-core, which will not exist for a SNAPSHOT version, so the build fails.

That's why [`BUILD.md`](https://github.com/ACINQ/phoenix/blob/master/BUILD.md#build-the-apk) mentions to first checkout a tag before running the docker release build. For now there is no tag where the new docker build works, so you cannot test the build. I'll update this issue to let you know when that's possible.

**Comment by dpad85** [comment]
Hi, starting from version `1.3.2` the docker release build should be much easier to run. You can check [BUILD.md](https://github.com/ACINQ/phoenix/blob/master/BUILD.md#build-the-apk) for more information.

**Comment by Giszmo** [comment]
I was able to reproduce the 1.3.3 release from Google Play. Congratulations! I will do my best to spread the word.
